### ISSUE TITLE
大佬，还差service的代码

### ISSUE THREAD

**Issue by zz-zc** [BuxsRen/CloudContent#1]
好像还差cloud-clipboard/internal/service里的代码没上传

**Comment by BuxsRen** [comment]
> 好像还差cloud-clipboard/internal/service里的代码没上传

service代码使用框架gf工具自动生成(goframe.org)
```shell
gf.exe gen service
```

**Comment by zz-zc** [comment]
> > 好像还差cloud-clipboard/internal/service里的代码没上传
> 
> service代码使用框架gf工具自动生成（goframe.org）
> 
> ```shell
> gf.exe gen service
> ```

感谢，忘了这茬了
